# ReplicaSet With Exits set based selector
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: nginx-app
 labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
     matchExpressions:
       - key : app
         operator: Exists

  template:
     metadata:
       name: nginx-temp
       labels:
          app: nginx-app
     spec:
       containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
          - containerPort: 80

  template:
     metadata:
       name: httpd-temp
       labels:
          app: httpd
     spec:
       containers:
        - name: httpd
          image: httpd:latest
          ports:
          - containerPort: 81
